#!/bin/bash

export S3_BUCKET_NAME="4652-5751-2377-rds-export2"
export S3_DIR_NAME="SDBA"
export APP_LIFECYCLE_TAG="remedy-lifecycle"
export AWS_DEFAULT_REGION="us-east-1"
export RDS_METADATA_FILENAME="${APP_LIFECYCLE_TAG}-db-metadata.json"
export SNAPSHOT_RETENTION_WEEKS="1"
export WEEK_TO_EXECUTE="all"
