#!/bin/bash

export S3_BUCKET_NAME="4652-5751-2377-rds-export"
export S3_DIR_NAME="SDBA"
export RDS_METADATA_FILENAME="rds-metadata.json"
export RDS_TAG_VALUE="RDS"
export AWS_DEFAULT_REGION="us-east-1"
